defaultProject: factory-etl-dev-0y1dhf
defaultDataset: factory_etl_silver
defaultAssertionDataset: factory_etl_assertions
defaultLocation: us-central1
vars:
  enableScd2: "true"
  enableLegacyFacts: "true"
  gcpProject: factory-etl-dev-0y1dhf
  bronzeBucket: factory-etl-dev-0y1dhf-bronze
  stagingDataset: factory_etl_bronze_stg
  silverDataset: factory_etl_silver
  goldDataset: factory_etl_gold
  securityDataset: factory_etl_security
