steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/factory-etl-dev-0y1dhf/factory-etl/factory-etl:latest', '-f', 'docker/Dockerfile', '.']
images:
  - 'us-central1-docker.pkg.dev/factory-etl-dev-0y1dhf/factory-etl/factory-etl:latest'
