config {
  type: "table",
  schema: "factory_etl_gold",
  name: "dim_empresa",
  description: "Tabla Maestra de Empresas: Mapea los códigos de base de datos source_empresa (tinito, ctb, daroan, roldan, ctm) con sus razones sociales y RIFs fiscales oficiales",
}

SELECT
  'tinito' AS source_empresa,
  'Comercial Tinito El Tigre' AS nombre_empresa,
  'Comercial Tinito El Tigre, C.A.' AS razon_social,
  'J310904553' AS rif_empresa,
  'ACTIVO' AS status,
  CURRENT_TIMESTAMP() AS fecha_actualizacion
UNION ALL
SELECT
  'ctb' AS source_empresa,
  'Comercial Tinito Barcelona' AS nombre_empresa,
  'Comercial Tinito Barcelona C.A.' AS razon_social,
  'J409990001' AS rif_empresa,
  'ACTIVO' AS status,
  CURRENT_TIMESTAMP() AS fecha_actualizacion
UNION ALL
SELECT
  'daroan' AS source_empresa,
  'Drinks and Food' AS nombre_empresa,
  'Drinks and Food C.A.' AS razon_social,
  'J501104921' AS rif_empresa,
  'ACTIVO' AS status,
  CURRENT_TIMESTAMP() AS fecha_actualizacion
UNION ALL
SELECT
  'ctm' AS source_empresa,
  'Comercial Tinito' AS nombre_empresa,
  'Comercial Tinito C.A.' AS razon_social,
  'J298069104' AS rif_empresa,
  'ACTIVO' AS status,
  CURRENT_TIMESTAMP() AS fecha_actualizacion
UNION ALL
SELECT
  'roldan' AS source_empresa,
  'Inversiones Roldan' AS nombre_empresa,
  'Inversiones Roldan, C.A.' AS razon_social,
  'J303949827' AS rif_empresa,
  'ACTIVO' AS status,
  CURRENT_TIMESTAMP() AS fecha_actualizacion
