config {
  type: "table",
  schema: "factory_etl_gold",
  name: "dim_cliente",
  description: "Dimensión de cliente en Gold con latitud, longitud y RIF",
  bigquery: {
    clusterBy: ["source_empresa", "cod_cli"]
  },
  assertions: {
    uniqueKey: ["source_empresa", "cod_cli"],
    nonNull: ["source_empresa", "cod_cli"]
  }
}

SELECT * REPLACE (CAST(gps AS STRING) AS gps)
FROM ${ref("sil_clientes")}
